### ISSUE TITLE
support for o-blog

### ISSUE THREAD

**Issue by paynito** [pschorf/spacemacs-layers#1]
I can't get a private layer working for a different blogging platform o-blog.  You seem smart enough to help.  http://renard.github.io/o-blog/  Do you have 5 mins?

**Comment by pschorf** [comment]
Sure, can you give me some more details on what you're trying to do?

**Comment by paynito** [comment]
I just followed the instructions there  
    cd ~/.emacs.d
    git clone https://github.com/renard/o-blog.git

And add following to your ~/.emacs.d/init.el file:

```
(add-to-list 'load-path "~/.emacs.d/o-blog")
(require 'o-blog)
```

I also tried cloning into ~/.emacs.d/private

but I can't run the example, 

```
 M-x org-publish-blog
```

org-publish-blog is not added to my meta-menu

**Comment by pschorf** [comment]
This looks like an issue with v1/v2 of o-blog. If you do the following instead, it worked for me:

```
cd ~/.emacs.d
git clone https://github.com/renard/o-blog.git
cd o-blog
git checkout o-blog-v1
```

Then add to init.el as described.
